import React,{useEffect,useMemo,useState} from 'react';
import {Link,NavLink,useNavigate} from 'react-router-dom';
import * as I from 'lucide-react';
import {api} from './api.js';
import {logoutFirebase} from './firebase-client.js';
import './app-styles.css';
import './customer-styles.css';

const menu=[['/customer','LayoutDashboard','Overview'],['/customer/jobs','BriefcaseBusiness','My Jobs'],['/customer/documents','FileText','Quotes & Invoices'],['/customer/systems','Cctv','My Systems'],['/customer/support','MessageSquarePlus','Service Requests']];
const money=value=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(value||0));
const date=value=>value?new Date(value).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'Not set';
const tone=status=>['Paid','Accepted','Completed','Resolved','Closed'].includes(status)?'green':['Overdue','Rejected','Urgent'].includes(status)?'red':['Sent','Scheduled','Reviewing'].includes(status)?'blue':'grey';

function usePortal(){const [data,setData]=useState(null),[error,setError]=useState('');const load=()=>api.portal.get().then(setData).catch(e=>setError(e.message));useEffect(()=>{load()},[]);return{data,error,load}}
function Badge({children}){return <span className={'app-badge '+tone(children)}>{children}</span>}
function Shell({children,title,subtitle}){const [open,setOpen]=useState(false),[me,setMe]=useState(null);const nav=useNavigate();useEffect(()=>{api.me().then(x=>setMe(x.user))},[]);const logout=async()=>{await logoutFirebase();nav('/login',{replace:true})};const initials=(me?.fullName||'Customer').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();return <div className="app-shell customer-shell"><aside className={open?'app-side open':'app-side'}><Link className="app-logo" to="/customer"><img src="/assets/logo.png" alt="SecureVision AI"/></Link><div className="customer-label"><I.UserRoundCheck/>Customer portal</div><nav>{menu.map(([to,icon,label])=>{const Icon=I[icon];return <NavLink key={to} end={to==='/customer'} to={to} onClick={()=>setOpen(false)}><Icon/><span>{label}</span></NavLink>})}</nav><div className="app-help"><I.ShieldCheck/><b>Private customer access</b><small>Only your organisation's records are visible.</small></div><button className="customer-logout" onClick={logout}><I.LogOut/>Sign out</button><div className="app-user"><div className="avatar">{initials}</div><span><b>{me?.fullName||'Customer'}</b><small>Customer</small></span></div></aside><div className="app-main"><header className="app-top"><button className="app-menu" onClick={()=>setOpen(!open)} aria-label="Open customer menu"><I.Menu/></button><div className="customer-top"><I.ShieldCheck/>Secure customer workspace</div><button className="round" onClick={logout} aria-label="Sign out" title="Sign out"><I.LogOut/></button><div className="top-avatar">{initials}</div></header><main className="app-content"><div className="app-heading"><div><h1>{title}</h1><p>{subtitle}</p></div></div>{children}</main></div></div>}
function Loading({error}){return <div className="customer-empty">{error?<I.TriangleAlert/>:<I.LoaderCircle className="spin"/>}<p>{error||'Loading your secure records…'}</p></div>}

export function CustomerDashboard(){const {data,error}=usePortal();if(!data)return <Shell title="Customer Portal" subtitle="Your service account at a glance."><Loading error={error}/></Shell>;const active=data.jobs.filter(x=>!['Completed','Cancelled'].includes(x.status));return <Shell title={`Welcome, ${data.customer.contactName}`} subtitle={`${data.customer.companyName} · Services provided by ${data.provider.name}`}><div className="metric-grid">{[[I.BriefcaseBusiness,'Active jobs',active.length],[I.FileCheck2,'Accepted quotes',data.quotes.filter(x=>x.status==='Accepted').length],[I.ReceiptPoundSterling,'Outstanding',money(data.invoices.reduce((n,x)=>n+x.balance,0))],[I.Cctv,'Installed systems',data.assets.length]].map(([Icon,label,value])=><article className="metric-card" key={label}><div className="metric-icon red"><Icon/></div><span><small>{label}</small><strong>{value}</strong></span></article>)}</div><div className="customer-grid"><section className="app-panel"><header><h2>Recent jobs</h2><Link to="/customer/jobs">View all</Link></header>{data.jobs.slice(0,4).map(x=><div className="portal-row" key={x.id}><I.BriefcaseBusiness/><span><b>{x.title}</b><small>{x.reference} · {x.siteName||'Site TBC'}</small></span><Badge>{x.status}</Badge></div>)}</section><section className="app-panel"><header><h2>Account</h2></header><div className="portal-account"><b>{data.customer.companyName}</b><p>{data.customer.address}</p><p>{data.customer.email}</p><p>{data.customer.phone}</p><hr/><small>Your service provider</small><b>{data.provider.name}</b><p>{data.provider.email} · {data.provider.phone}</p></div></section></div></Shell>}

export function CustomerJobs(){const {data,error}=usePortal();return <Shell title="My Jobs" subtitle="Track scheduled, active and completed work.">{!data?<Loading error={error}/>:<section className="app-panel portal-list">{data.jobs.map(x=><article key={x.id}><div><small>{x.reference}</small><h3>{x.title}</h3><p><I.MapPin/> {x.siteName||'Site TBC'} · {x.scheduledStart?`${date(x.scheduledStart)} at ${new Date(x.scheduledStart).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}`:`Due ${date(x.dueDate)}`}</p></div><Badge>{x.status}</Badge>{x.reportReady&&<button className="app-button secondary" onClick={()=>api.portal.downloadReport(x.id,x.reference)}><I.Download/>Service Report</button>}</article>)}</section>}</Shell>}

export function CustomerDocuments(){const {data,error}=usePortal();const [tab,setTab]=useState('quotes');return <Shell title="Quotes & Invoices" subtitle="View and download your commercial documents.">{!data?<Loading error={error}/>:<><div className="segmented portal-tabs"><button className={tab==='quotes'?'active':''} onClick={()=>setTab('quotes')}>Quotes</button><button className={tab==='invoices'?'active':''} onClick={()=>setTab('invoices')}>Invoices</button></div><section className="app-panel portal-list">{data[tab].map(x=><article key={x.id}><div><small>{x.reference}</small><h3>{x.title||`Invoice ${x.reference}`}</h3><p>{tab==='quotes'?`Valid until ${date(x.validUntil)}`:`Due ${date(x.dueAt)}`}</p></div><strong>{money(x.total)}</strong><Badge>{x.status}</Badge><button className="app-button secondary" onClick={()=>tab==='quotes'?api.portal.downloadQuote(x.id,x.reference):api.portal.downloadInvoice(x.id,x.reference)}><I.Download/>PDF</button></article>)}</section></>}</Shell>}

export function CustomerSystems(){const {data,error}=usePortal();return <Shell title="My Systems" subtitle="Installed equipment, warranties and maintenance information.">{!data?<Loading error={error}/>:<div className="portal-system-grid">{data.assets.map(x=><article className="app-panel" key={x.id}><I.Cctv/><small>{x.siteName||'Site not assigned'}</small><h3>{x.systemType}</h3><p>{[x.manufacturer,x.model].filter(Boolean).join(' · ')||'Details not recorded'}</p><dl><dt>Serial number</dt><dd>{x.serialNumber||'—'}</dd><dt>Installed</dt><dd>{date(x.installedAt)}</dd><dt>Warranty expires</dt><dd>{date(x.warrantyExpiresAt)}</dd><dt>Maintenance due</dt><dd>{date(x.maintenanceDueAt)}</dd></dl></article>)}{!data.assets.length&&<div className="customer-empty"><I.Cctv/><p>No installed systems have been recorded yet.</p></div>}</div>}</Shell>}

export function CustomerSupport(){const {data,error,load}=usePortal();const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);const form=Object.fromEntries(new FormData(e.currentTarget));form.siteId=form.siteId||null;try{await api.portal.createRequest(form);e.currentTarget.reset();setNotice('Your service request has been submitted.');await load()}catch(problem){setNotice(problem.message)}finally{setBusy(false)}};return <Shell title="Service Requests" subtitle="Request assistance from your security service provider.">{!data?<Loading error={error}/>:<div className="customer-grid"><form className="app-panel portal-request" onSubmit={submit}><header><h2>New request</h2></header><label>Site<select name="siteId"><option value="">General / no site</option>{data.sites.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Subject<input name="subject" required minLength="3"/></label><label>Priority<select name="priority" defaultValue="Normal"><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></label><label>Description<textarea name="description" required minLength="10" placeholder="Describe the fault, request or assistance required…"/></label>{notice&&<div className="connection-note">{notice}</div>}<button className="app-button" disabled={busy}><I.Send/>{busy?'Submitting…':'Submit Request'}</button></form><section className="app-panel"><header><h2>Request history</h2></header>{data.requests.map(x=><div className="portal-row" key={x.id}><I.MessageSquareText/><span><b>{x.subject}</b><small>{x.siteName||'General'} · {date(x.createdAt)}</small></span><Badge>{x.status}</Badge></div>)}</section></div>}</Shell>}
