import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import * as I from 'lucide-react';
import {AppShell} from './app-pages.jsx';
import {api} from './api.js';

const Badge=({children})=><span className={'app-badge '+(children==='Urgent'?'red':children==='High'?'amber':['Resolved','Closed'].includes(children)?'green':children==='Scheduled'?'blue':'grey')}>{children}</span>;
const date=value=>new Date(value).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'});

export function ServiceRequestInbox(){
  const [rows,setRows]=useState([]),[engineers,setEngineers]=useState([]),[selected,setSelected]=useState(null),[notice,setNotice]=useState('Loading customer requests…'),[busy,setBusy]=useState(false);
  const load=()=>Promise.all([api.serviceRequests.list(),api.engineers.list()]).then(([requests,team])=>{setRows(requests);setEngineers(team);setNotice('Customer service requests connected to PostgreSQL')}).catch(e=>setNotice(e.message));
  useEffect(()=>{load()},[]);
  const update=async(row,key,value)=>{try{await api.serviceRequests.update(row.id,{status:key==='status'?value:row.status,priority:key==='priority'?value:row.priority});await load()}catch(e){setNotice(e.message)}};
  const createJob=async e=>{e.preventDefault();setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));data.engineerId=data.engineerId||null;for(const key of ['scheduledStart','scheduledEnd'])data[key]=data[key]?new Date(data[key]).toISOString():null;try{const job=await api.serviceRequests.toJob(selected.id,data);setNotice(`${job.reference} created from the customer request.`);setSelected(null);await load()}catch(error){setNotice(error.message)}finally{setBusy(false)}};
  return <AppShell title="Service Requests" subtitle="Review customer requests and turn approved work into scheduled jobs."><div className="connection-note"><I.MessageSquareText/>{notice}</div><div className="metric-grid">{[[I.Inbox,'New',rows.filter(x=>x.status==='Submitted').length],[I.SearchCheck,'Reviewing',rows.filter(x=>x.status==='Reviewing').length],[I.CalendarCheck,'Scheduled',rows.filter(x=>x.status==='Scheduled').length],[I.CircleCheckBig,'Resolved',rows.filter(x=>['Resolved','Closed'].includes(x.status)).length]].map(([Icon,label,value])=><article className="metric-card" key={label}><div className="metric-icon red"><Icon/></div><span><small>{label}</small><strong>{value}</strong></span></article>)}</div><section className="app-panel request-inbox"><header><h2>Customer request inbox</h2><span>{rows.length} total</span></header>{rows.map(row=><article key={row.id}><div className="request-main"><div><Badge>{row.priority}</Badge><small>{date(row.createdAt)}</small></div><h3>{row.subject}</h3><p>{row.description}</p><small><I.Building2/> {row.customerName} · {row.siteName||'General request'}</small></div><div className="request-controls"><label>Status<select value={row.status} onChange={e=>update(row,'status',e.target.value)}><option>Submitted</option><option>Reviewing</option><option>Scheduled</option><option>Resolved</option><option>Closed</option></select></label><label>Priority<select value={row.priority} onChange={e=>update(row,'priority',e.target.value)}><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></label>{row.jobId?<Link className="app-button secondary" to={`/app/jobs/${row.jobId}`}><I.BriefcaseBusiness/>View {row.jobReference}</Link>:<button className="app-button" onClick={()=>setSelected(row)}><I.Plus/>Create Job</button>}</div></article>)}{!rows.length&&<div className="crm-empty">No customer service requests have been submitted.</div>}</section>{selected&&<div className="app-modal-backdrop"><form className="app-modal" onSubmit={createJob}><header><div><h2>Create job from request</h2><p>{selected.customerName} · {selected.subject}</p></div><button type="button" onClick={()=>setSelected(null)}><I.X/></button></header><div className="modal-grid"><label>Engineer<select name="engineerId"><option value="">Unassigned</option>{engineers.map(x=><option value={x.id} key={x.id}>{x.fullName} · {x.status}</option>)}</select></label><label>Due date<input name="dueDate" type="date" required/></label><label>Scheduled start<input name="scheduledStart" type="datetime-local"/></label><label>Scheduled end<input name="scheduledEnd" type="datetime-local"/></label></div><footer><button type="button" className="app-button secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="app-button" disabled={busy}>{busy?'Creating…':'Create Job'}</button></footer></form></div>}</AppShell>;
}
