import {config} from './config.js';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

export async function sendDocumentEmail({document,pdf,delivery}){
  if(!config.resendApiKey)throw Object.assign(new Error('Resend is not configured.'),{status:503});
  const isQuote=document.type==='quote';
  const action=isQuote?`<a href="${config.appPublicUrl}/quote/${delivery.accessToken}" style="display:inline-block;background:#ed1b2f;color:#fff;text-decoration:none;padding:13px 22px;border-radius:6px;font-weight:700">Review quotation</a>`:'';
  const html=`<!doctype html><html><body style="margin:0;background:#f3f4f6;font-family:Arial,sans-serif;color:#17181b"><div style="max-width:640px;margin:30px auto;background:#fff;border-radius:10px;overflow:hidden"><div style="background:#090a0c;padding:24px;color:#fff;border-bottom:4px solid #ed1b2f"><h1 style="margin:0;font-size:22px">${escapeHtml(document.company.name)}</h1><small>Sent securely using SecureVision AI</small></div><div style="padding:30px"><p>Hello ${escapeHtml(document.customer.contact||document.customer.name)},</p><p>Please find ${isQuote?'quotation':'invoice'} <b>${escapeHtml(document.reference)}</b> from ${escapeHtml(document.company.name)} attached.</p><p style="font-size:22px"><b>Total: GBP ${document.total.toFixed(2)}</b></p>${action}<p style="margin-top:28px;color:#666">Questions? Reply directly to this email to contact ${escapeHtml(document.company.name)}.</p></div></div></body></html>`;
  const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${config.resendApiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from:config.emailFrom,to:[document.customer.email],reply_to:document.company.email||undefined,subject:`${document.company.name} - ${isQuote?'Quotation':'Invoice'} ${document.reference}`,html,attachments:[{filename:`${document.reference}.pdf`,content:pdf.toString('base64')}]})});
  const result=await response.json().catch(()=>({}));
  if(!response.ok)throw Object.assign(new Error(result.message||`Resend rejected the email (${response.status}).`),{status:502});
  return result;
}

export async function sendEngineerJobEmail(data){
  if(!config.resendApiKey)throw Object.assign(new Error('Resend is not configured.'),{status:503});
  const job=data.job;
  const schedule=job.scheduledStart?`${new Date(job.scheduledStart).toLocaleString('en-GB')} to ${new Date(job.scheduledEnd).toLocaleString('en-GB')}`:`Due by ${new Date(job.dueDate).toLocaleDateString('en-GB')}`;
  const html=`<!doctype html><html><body style="margin:0;background:#f3f4f6;font-family:Arial,sans-serif;color:#17181b"><div style="max-width:620px;margin:30px auto;background:#fff;border-radius:10px;overflow:hidden"><div style="background:#090a0c;padding:24px;color:#fff;border-bottom:4px solid #ed1b2f"><h1 style="margin:0;font-size:22px">${escapeHtml(data.companyName)}</h1><small>New engineer assignment</small></div><div style="padding:30px"><p>Hello ${escapeHtml(data.engineerName)},</p><p>You have been assigned job <b>${escapeHtml(job.reference)}</b>, created from accepted quotation ${escapeHtml(data.quoteReference)}.</p><table style="width:100%;border-collapse:collapse"><tr><td style="padding:10px;border-bottom:1px solid #ddd"><b>Customer</b></td><td style="padding:10px;border-bottom:1px solid #ddd">${escapeHtml(data.customerName)}</td></tr><tr><td style="padding:10px;border-bottom:1px solid #ddd"><b>Job</b></td><td style="padding:10px;border-bottom:1px solid #ddd">${escapeHtml(job.title)}</td></tr><tr><td style="padding:10px;border-bottom:1px solid #ddd"><b>Schedule</b></td><td style="padding:10px;border-bottom:1px solid #ddd">${escapeHtml(schedule)}</td></tr><tr><td style="padding:10px;border-bottom:1px solid #ddd"><b>Priority</b></td><td style="padding:10px;border-bottom:1px solid #ddd">${escapeHtml(job.priority)}</td></tr></table><a href="${config.appPublicUrl}/app/jobs/${job.id}" style="display:inline-block;margin-top:24px;background:#ed1b2f;color:#fff;text-decoration:none;padding:13px 22px;border-radius:6px;font-weight:700">Open job</a></div></div></body></html>`;
  const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${config.resendApiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from:config.emailFrom,to:[data.engineerEmail],subject:`New job assignment: ${job.reference} - ${job.title}`,html})});
  const result=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(result.message||`Resend rejected the engineer notification (${response.status}).`);
  return result;
}

export async function sendServiceReportEmail({report,pdf}){
  if(!config.resendApiKey)throw Object.assign(new Error('Resend is not configured.'),{status:503});
  if(!report.customer.email)throw Object.assign(new Error('This customer does not have an email address.'),{status:400});
  const html=`<!doctype html><html><body style="margin:0;background:#f3f4f6;font-family:Arial,sans-serif;color:#17181b"><div style="max-width:640px;margin:30px auto;background:#fff;border-radius:10px;overflow:hidden"><div style="background:#090a0c;padding:24px;color:#fff;border-bottom:4px solid #ed1b2f"><h1 style="margin:0;font-size:22px">${escapeHtml(report.company.name)}</h1><small>Service completion report</small></div><div style="padding:30px"><p>Hello ${escapeHtml(report.customer.name||report.customer.company)},</p><p>Please find the completed service report for job <b>${escapeHtml(report.reference)}</b> attached.</p><p><b>${escapeHtml(report.title)}</b></p><p>The report includes the engineer's work summary, completion checklist, equipment details, customer sign-off and site evidence.</p><p style="margin-top:28px;color:#666">Questions? Reply directly to contact ${escapeHtml(report.company.name)}.</p></div></div></body></html>`;
  const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${config.resendApiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from:config.emailFrom,to:[report.customer.email],reply_to:report.company.email||undefined,subject:`${report.company.name} - Service Report ${report.reference}`,html,attachments:[{filename:`${report.reference}-service-report.pdf`,content:pdf.toString('base64')}]})});
  const result=await response.json().catch(()=>({}));
  if(!response.ok)throw Object.assign(new Error(result.message||`Resend rejected the service report (${response.status}).`),{status:502});
  return result;
}

export async function sendContactEmail(enquiry){
  if(!config.resendApiKey)throw Object.assign(new Error('Email delivery is not configured.'),{status:503});
  if(!config.contactToEmail)throw Object.assign(new Error('The contact recipient has not been configured.'),{status:503});
  const html=`<!doctype html><html><body style="margin:0;background:#f3f4f6;font-family:Arial,sans-serif;color:#17181b"><div style="max-width:640px;margin:30px auto;background:#fff;border-radius:10px;overflow:hidden"><div style="background:#090a0c;padding:24px;color:#fff;border-bottom:4px solid #ed1b2f"><h1 style="margin:0;font-size:22px">SecureVision AI enquiry</h1><small>Submitted through the public website</small></div><div style="padding:30px"><p><b>From:</b> ${escapeHtml(enquiry.fullName)}</p><p><b>Company:</b> ${escapeHtml(enquiry.companyName||'Not provided')}</p><p><b>Email:</b> ${escapeHtml(enquiry.email)}</p><p><b>Phone:</b> ${escapeHtml(enquiry.phone||'Not provided')}</p><p><b>Subject:</b> ${escapeHtml(enquiry.subject)}</p><hr style="border:0;border-top:1px solid #ddd"><p style="white-space:pre-wrap">${escapeHtml(enquiry.message)}</p></div></div></body></html>`;
  const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${config.resendApiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from:config.emailFrom,to:[config.contactToEmail],reply_to:enquiry.email,subject:`Website enquiry: ${enquiry.subject}`,html})});
  const result=await response.json().catch(()=>({}));
  if(!response.ok)throw Object.assign(new Error(result.message||`Resend rejected the enquiry (${response.status}).`),{status:502});
  return result;
}

export async function sendAppointmentReminder(job){
  if(!config.resendApiKey)throw Object.assign(new Error('Resend is not configured.'),{status:503});
  const start=new Date(job.scheduledStart).toLocaleString('en-GB',{dateStyle:'full',timeStyle:'short'}),end=job.scheduledEnd?new Date(job.scheduledEnd).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):null;
  const location=[job.siteName,job.siteAddress,job.sitePostcode].filter(Boolean).join(', ')||'Please contact us to confirm the site address.';
  const html=`<!doctype html><html><body style="margin:0;background:#f3f4f6;font-family:Arial,sans-serif;color:#17181b"><div style="max-width:640px;margin:30px auto;background:#fff;border-radius:10px;overflow:hidden"><div style="background:#090a0c;padding:24px;color:#fff;border-bottom:4px solid #ed1b2f"><h1 style="margin:0;font-size:22px">${escapeHtml(job.companyName)}</h1><small>Appointment reminder</small></div><div style="padding:30px"><p>Hello ${escapeHtml(job.contactName||job.customerName)},</p><p>This is a reminder about your scheduled security service appointment.</p><table style="width:100%;border-collapse:collapse"><tr><td style="padding:10px;border-bottom:1px solid #ddd"><b>Reference</b></td><td style="padding:10px;border-bottom:1px solid #ddd">${escapeHtml(job.reference)}</td></tr><tr><td style="padding:10px;border-bottom:1px solid #ddd"><b>Work</b></td><td style="padding:10px;border-bottom:1px solid #ddd">${escapeHtml(job.title)}</td></tr><tr><td style="padding:10px;border-bottom:1px solid #ddd"><b>Date and time</b></td><td style="padding:10px;border-bottom:1px solid #ddd">${escapeHtml(start)}${end?` until ${escapeHtml(end)}`:''}</td></tr><tr><td style="padding:10px;border-bottom:1px solid #ddd"><b>Location</b></td><td style="padding:10px;border-bottom:1px solid #ddd">${escapeHtml(location)}</td></tr><tr><td style="padding:10px;border-bottom:1px solid #ddd"><b>Engineer</b></td><td style="padding:10px;border-bottom:1px solid #ddd">${escapeHtml(job.engineerName)}</td></tr></table><p style="margin-top:24px;color:#666">If access arrangements have changed, reply to this email to contact ${escapeHtml(job.companyName)}.</p></div></div></body></html>`;
  const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${config.resendApiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from:config.emailFrom,to:[job.email],reply_to:job.companyEmail||undefined,subject:`Appointment reminder: ${job.reference} - ${job.title}`,html})});
  const result=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(result.message||`Resend rejected the reminder (${response.status}).`),{status:502});return result;
}
