import {randomUUID} from 'node:crypto';
import {pool,query} from './db.js';

const customerSeed=[
  {id:randomUUID(),companyName:'Oakfield Business Park',contactName:'Sarah Mitchell',email:'sarah@example.com',phone:'',status:'Active',address:'Birmingham',sites:4,totalValue:12480},
  {id:randomUUID(),companyName:'Vector Logistics Ltd',contactName:'Mark Thompson',email:'mark@example.com',phone:'',status:'Active',address:'Coventry',sites:2,totalValue:8720},
  {id:randomUUID(),companyName:'Westfield Stores',contactName:'Olivia Harris',email:'olivia@example.com',phone:'',status:'Active',address:'Birmingham',sites:8,totalValue:21350},
];
const jobSeed=[
  {id:randomUUID(),reference:'SV-1042',customerId:customerSeed[0].id,customerName:customerSeed[0].companyName,title:'Site Survey - Office Complex',description:'Survey CCTV coverage and cable routes.',engineerName:'James Wilson',dueDate:'2026-07-24',status:'Scheduled',priority:'High'},
  {id:randomUUID(),reference:'IN-1041',customerId:customerSeed[1].id,customerName:customerSeed[1].companyName,title:'CCTV Installation - Warehouse',description:'Install and commission eight cameras.',engineerName:'Liam Carter',dueDate:'2026-07-24',status:'In Progress',priority:'High'},
  {id:randomUUID(),reference:'MA-1040',customerId:customerSeed[2].id,customerName:customerSeed[2].companyName,title:'Alarm Maintenance - Retail',description:'Annual preventive maintenance.',engineerName:'Sophie Brown',dueDate:'2026-07-25',status:'Pending',priority:'Medium'},
];
let customers=structuredClone(customerSeed),jobs=structuredClone(jobSeed);

const mapCustomer=r=>({id:r.id,companyName:r.company_name,contactName:r.contact_name,email:r.email,phone:r.phone,status:r.status,address:r.address,sites:Number(r.sites_count||0),totalValue:Number(r.total_value||0),createdAt:r.created_at});
const mapJob=r=>({id:r.id,reference:r.reference,customerId:r.customer_id,customerName:r.customer_name,siteId:r.site_id,siteName:r.site_name,title:r.title,description:r.description,engineerName:r.engineer_name,engineerUid:r.assigned_engineer_uid,engineerProfileId:r.engineer_profile_id,jobType:r.job_type,dueDate:r.due_date,scheduledStart:r.scheduled_start,scheduledEnd:r.scheduled_end,status:r.status,priority:r.priority,createdAt:r.created_at});
const money=value=>Math.round(Number(value)*100)/100;

export const store={
  async updateMyAccount(data,user){if(!pool)return{...user,...data};const r=await query('update app_users set full_name=$2,updated_at=now() where firebase_uid=$1 returning firebase_uid uid,email,full_name "fullName",role,company_id "companyId",is_active "isActive"',[user.uid,data.fullName]);return r.rows[0]||{...user,...data};},
  async getCompany(user){if(!pool||!user.companyId)return null;const r=await query('select * from companies where id=$1',[user.companyId]);if(!r.rowCount)return null;const services=await query('select service from company_services where company_id=$1 order by service',[user.companyId]);const c=r.rows[0];return{id:c.id,name:c.name,email:c.email,phone:c.phone,website:c.website,address:c.address,timezone:c.timezone,currency:c.currency,hasLogo:Boolean(c.logo_data),logoUpdatedAt:c.logo_updated_at,services:services.rows.map(x=>x.service)};},
  async getBilling(user){if(!pool||!user.companyId)return{plan:'Professional',billingEmail:user.email,purchaseOrderReference:'',status:'Prototype'};const r=await query('select billing_plan "plan",coalesce(nullif(billing_email,\'\'),email) "billingEmail",purchase_order_reference "purchaseOrderReference" from companies where id=$1',[user.companyId]);return r.rows[0]?{...r.rows[0],status:'Prototype'}:null;},
  async saveBilling(data,user){if(!pool)return{...data,status:'Prototype'};const r=await query('update companies set billing_plan=$2,billing_email=$3,purchase_order_reference=$4,updated_at=now() where id=$1 returning billing_plan "plan",billing_email "billingEmail",purchase_order_reference "purchaseOrderReference"',[user.companyId,data.plan,data.billingEmail,data.purchaseOrderReference]);if(!r.rowCount)throw Object.assign(new Error('Complete the company profile before saving billing preferences.'),{status:409});return{...r.rows[0],status:'Prototype'};},
  async getCompanyLogo(user){if(!pool||!user.companyId)return null;const r=await query('select logo_data,logo_mime from companies where id=$1 and logo_data is not null',[user.companyId]);return r.rowCount?{data:r.rows[0].logo_data,mime:r.rows[0].logo_mime}:null;},
  async saveCompanyLogo(data,mime,user){if(!pool||!user.companyId)return null;const r=await query('update companies set logo_data=$2,logo_mime=$3,logo_updated_at=now(),updated_at=now() where id=$1 returning id,logo_updated_at "logoUpdatedAt"',[user.companyId,data,mime]);return r.rows[0]||null;},
  async saveCompany(data,user){if(!pool)return{id:'local-company',...data};const client=await pool.connect();try{await client.query('begin');let r;if(user.companyId){r=await client.query('update companies set name=$2,email=$3,phone=$4,website=$5,address=$6,timezone=$7,currency=$8,updated_at=now() where id=$1 returning *',[user.companyId,data.name,data.email,data.phone,data.website,data.address,data.timezone,data.currency]);}else{r=await client.query('insert into companies(name,email,phone,website,address,timezone,currency,created_by) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[data.name,data.email,data.phone,data.website,data.address,data.timezone,data.currency,user.uid]);await client.query('update app_users set company_id=$2 where firebase_uid=$1',[user.uid,r.rows[0].id]);user.companyId=r.rows[0].id;}await client.query('delete from company_services where company_id=$1',[user.companyId]);for(const service of data.services)await client.query('insert into company_services(company_id,service) values($1,$2)',[user.companyId,service]);await client.query('commit');return{id:r.rows[0].id,...data};}catch(error){await client.query('rollback');throw error;}finally{client.release();}},
  async listCustomers(search='',user={}){if(!pool)return customers.filter(c=>JSON.stringify(c).toLowerCase().includes(search.toLowerCase()));if(!user.companyId)return[];const r=await query(`select c.*,count(distinct s.id)::int sites_count,coalesce(sum(i.total) filter(where i.status='Paid'),0) total_value from customers c left join customer_sites s on s.customer_id=c.id left join invoices i on i.customer_id=c.id where c.company_id=$2 and ($1='' or c.company_name ilike '%'||$1||'%' or c.contact_name ilike '%'||$1||'%' or c.email ilike '%'||$1||'%') group by c.id order by c.created_at desc`,[search,user.companyId]);return r.rows.map(mapCustomer);},
  async createCustomer(data,user){if(!pool){const row={id:randomUUID(),...data,sites:0,totalValue:0,createdAt:new Date().toISOString(),createdBy:user.uid};customers.unshift(row);return row;}if(!user.companyId)throw Object.assign(new Error('Complete company onboarding first.'),{status:409});const r=await query('insert into customers(company_name,contact_name,email,phone,status,address,created_by,company_id) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[data.companyName,data.contactName,data.email,data.phone,data.status,data.address,user.uid,user.companyId]);return mapCustomer(r.rows[0]);},
  async getCustomer(id,user){if(!pool)return customers.find(x=>x.id===id)||null;const customer=await query('select * from customers where id=$1 and company_id=$2',[id,user.companyId]);if(!customer.rowCount)return null;const [contacts,sites,assets,jobsResult]=await Promise.all([query(`select id,full_name "fullName",job_title "jobTitle",email,phone,contact_type "contactType",is_primary "isPrimary" from customer_contacts where customer_id=$1 and company_id=$2 order by is_primary desc,created_at`,[id,user.companyId]),query(`select id,name,address,postcode,access_instructions "accessInstructions",opening_hours "openingHours",notes from customer_sites where customer_id=$1 and company_id=$2 order by created_at`,[id,user.companyId]),query(`select id,site_id "siteId",system_type "systemType",manufacturer,model,serial_number "serialNumber",installed_at "installedAt",warranty_expires_at "warrantyExpiresAt",maintenance_due_at "maintenanceDueAt",notes from customer_assets where customer_id=$1 and company_id=$2 order by created_at desc`,[id,user.companyId]),query(`select id,reference,title,status,due_date "dueDate" from jobs where customer_id=$1 and company_id=$2 order by created_at desc limit 20`,[id,user.companyId])]);const c=customer.rows[0];const primary={id:'primary',fullName:c.contact_name,jobTitle:'Primary contact',email:c.email,phone:c.phone,contactType:'General',isPrimary:true};return{...mapCustomer(c),billingEmail:c.billing_email,notes:c.notes,contacts:contacts.rowCount?contacts.rows:[primary],sites:sites.rows,assets:assets.rows,jobs:jobsResult.rows};},
  async createContact(customerId,data,user){if(!pool)return{id:randomUUID(),...data};const owner=await query('select 1 from customers where id=$1 and company_id=$2',[customerId,user.companyId]);if(!owner.rowCount)return null;if(data.isPrimary)await query('update customer_contacts set is_primary=false where customer_id=$1 and company_id=$2',[customerId,user.companyId]);const r=await query(`insert into customer_contacts(company_id,customer_id,full_name,job_title,email,phone,contact_type,is_primary) values($1,$2,$3,$4,$5,$6,$7,$8) returning id,full_name "fullName",job_title "jobTitle",email,phone,contact_type "contactType",is_primary "isPrimary"`,[user.companyId,customerId,data.fullName,data.jobTitle,data.email,data.phone,data.contactType,data.isPrimary]);return r.rows[0];},
  async createSite(customerId,data,user){if(!pool)return{id:randomUUID(),...data};const r=await query(`insert into customer_sites(company_id,customer_id,name,address,postcode,access_instructions,opening_hours,notes) select $2,id,$3,$4,$5,$6,$7,$8 from customers where id=$1 and company_id=$2 returning id,name,address,postcode,access_instructions "accessInstructions",opening_hours "openingHours",notes`,[customerId,user.companyId,data.name,data.address,data.postcode,data.accessInstructions,data.openingHours,data.notes]);return r.rows[0]||null;},
  async createAsset(customerId,data,user){if(!pool)return{id:randomUUID(),...data};if(data.siteId){const site=await query('select 1 from customer_sites where id=$1 and customer_id=$2 and company_id=$3',[data.siteId,customerId,user.companyId]);if(!site.rowCount)return null;}const owner=await query('select 1 from customers where id=$1 and company_id=$2',[customerId,user.companyId]);if(!owner.rowCount)return null;const r=await query(`insert into customer_assets(company_id,customer_id,site_id,system_type,manufacturer,model,serial_number,installed_at,warranty_expires_at,maintenance_due_at,notes) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning id,site_id "siteId",system_type "systemType",manufacturer,model,serial_number "serialNumber",installed_at "installedAt",warranty_expires_at "warrantyExpiresAt",maintenance_due_at "maintenanceDueAt",notes`,[user.companyId,customerId,data.siteId,data.systemType,data.manufacturer,data.model,data.serialNumber,data.installedAt,data.warrantyExpiresAt,data.maintenanceDueAt,data.notes]);return r.rows[0];},
  async updateCustomer(id,data,user={}){if(!pool){const i=customers.findIndex(c=>c.id===id);if(i<0)return null;customers[i]={...customers[i],...data};return customers[i];}const r=await query('update customers set company_name=$3,contact_name=$4,email=$5,phone=$6,status=$7,address=$8,updated_at=now() where id=$1 and company_id=$2 returning *',[id,user.companyId,data.companyName,data.contactName,data.email,data.phone,data.status,data.address]);return r.rowCount?mapCustomer(r.rows[0]):null;},
  async deleteCustomer(id,user={}){if(!pool){const before=customers.length;customers=customers.filter(c=>c.id!==id);return customers.length<before;}const r=await query('update customers set status=\'Inactive\',updated_at=now() where id=$1 and company_id=$2',[id,user.companyId]);return r.rowCount>0;},
  async listJobs(search='',user={}){if(!pool)return jobs.filter(j=>JSON.stringify(j).toLowerCase().includes(search.toLowerCase()));if(!user.companyId)return[];const r=await query(`select j.*,c.company_name customer_name,s.name site_name from jobs j join customers c on c.id=j.customer_id left join customer_sites s on s.id=j.site_id where j.company_id=$2 and ($3<>'engineer' or j.assigned_engineer_uid=$4 or exists(select 1 from engineer_profiles ep where ep.id=j.engineer_profile_id and ep.user_uid=$4)) and ($1='' or j.reference ilike '%'||$1||'%' or j.title ilike '%'||$1||'%' or c.company_name ilike '%'||$1||'%') order by coalesce(j.scheduled_start,j.due_date::timestamp),j.created_at desc`,[search,user.companyId,user.role,user.uid]);return r.rows.map(mapJob);},
  async createJob(data,user){if(!pool){const customer=customers.find(c=>c.id===data.customerId);if(!customer)return null;const row={id:randomUUID(),reference:`JOB-${String(jobs.length+1043).padStart(4,'0')}`,...data,dueDate:data.dueDate.toISOString().slice(0,10),customerName:customer.companyName,createdBy:user.uid};jobs.unshift(row);return row;}if(!user.companyId)throw Object.assign(new Error('Complete company onboarding first.'),{status:409});if(data.siteId){const site=await query('select 1 from customer_sites where id=$1 and customer_id=$2 and company_id=$3',[data.siteId,data.customerId,user.companyId]);if(!site.rowCount)return null;}let engineerName=data.engineerName;if(data.engineerUid){const engineer=await query(`select full_name from app_users where firebase_uid=$1 and company_id=$2 and role='engineer' and is_active=true`,[data.engineerUid,user.companyId]);if(!engineer.rowCount)return null;engineerName=engineer.rows[0].full_name;}const r=await query(`insert into jobs(reference,customer_id,site_id,title,description,engineer_name,assigned_engineer_uid,job_type,due_date,scheduled_start,scheduled_end,status,priority,created_by,company_id) select 'JOB-'||lpad(nextval('job_reference_seq')::text,4,'0'),id,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14 from customers where id=$1 and company_id=$14 returning *`,[data.customerId,data.siteId,data.title,data.description,engineerName,data.engineerUid,data.jobType,data.dueDate,data.scheduledStart,data.scheduledEnd,data.status,data.priority,user.uid,user.companyId]);if(!r.rowCount)return null;await query('insert into job_status_history(company_id,job_id,to_status,changed_by,note) values($1,$2,$3,$4,$5)',[user.companyId,r.rows[0].id,data.status,user.uid,'Job created']);const customer=await query('select company_name from customers where id=$1 and company_id=$2',[data.customerId,user.companyId]);return mapJob({...r.rows[0],customer_name:customer.rows[0]?.company_name});},
  async getJob(id,user){if(!pool)return jobs.find(x=>x.id===id)||null;const r=await query(`select j.*,c.company_name customer_name,s.name site_name,s.address site_address,s.postcode site_postcode,s.access_instructions from jobs j join customers c on c.id=j.customer_id left join customer_sites s on s.id=j.site_id where j.id=$1 and j.company_id=$2 and ($3<>'engineer' or j.assigned_engineer_uid=$4 or exists(select 1 from engineer_profiles ep where ep.id=j.engineer_profile_id and ep.user_uid=$4))`,[id,user.companyId,user.role,user.uid]);if(!r.rowCount)return null;const [history,notes,sites,engineers]=await Promise.all([query(`select from_status "fromStatus",to_status "toStatus",note,created_at "createdAt" from job_status_history where job_id=$1 and company_id=$2 order by created_at desc`,[id,user.companyId]),query(`select n.id,n.body,n.created_at "createdAt",coalesce(u.full_name,'Team member') author from job_notes n left join app_users u on u.firebase_uid=n.author_uid where n.job_id=$1 and n.company_id=$2 order by n.created_at desc`,[id,user.companyId]),user.role==='engineer'?Promise.resolve({rows:[]}):query('select id,name,address from customer_sites where customer_id=$1 and company_id=$2 order by name',[r.rows[0].customer_id,user.companyId]),user.role==='engineer'?Promise.resolve({rows:[]}):query(`select firebase_uid uid,full_name "fullName" from app_users where company_id=$1 and role='engineer' and is_active=true order by full_name`,[user.companyId])]);return{...mapJob(r.rows[0]),siteAddress:r.rows[0].site_address,sitePostcode:r.rows[0].site_postcode,accessInstructions:r.rows[0].access_instructions,history:history.rows,notes:notes.rows,sites:sites.rows,engineers:engineers.rows};},
  async updateJobStatus(id,status,user={}){if(status==='Completed')throw Object.assign(new Error('Complete the checklist, work summary and customer sign-off before closing this job.'),{status:400});if(!pool){const row=jobs.find(j=>j.id===id);if(!row)return null;row.status=status;return row;}const client=await pool.connect();try{await client.query('begin');const current=await client.query(`select status,customer_id from jobs j where id=$1 and company_id=$2 and ($3<>'engineer' or assigned_engineer_uid=$4 or exists(select 1 from engineer_profiles ep where ep.id=j.engineer_profile_id and ep.user_uid=$4)) for update`,[id,user.companyId,user.role,user.uid]);if(!current.rowCount){await client.query('rollback');return null}const r=await client.query(`update jobs set status=$2::job_status,updated_at=now() where id=$1 and company_id=$3 returning *`,[id,status,user.companyId]);await client.query('insert into job_status_history(company_id,job_id,from_status,to_status,changed_by) values($1,$2,$3,$4,$5)',[user.companyId,id,current.rows[0].status,status,user.uid]);await client.query('commit');const c=await query('select company_name from customers where id=$1 and company_id=$2',[r.rows[0].customer_id,user.companyId]);return mapJob({...r.rows[0],customer_name:c.rows[0]?.company_name});}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async scheduleJob(id,data,user){if(!pool)return null;if(data.siteId){const job=await query('select customer_id from jobs where id=$1 and company_id=$2',[id,user.companyId]);if(!job.rowCount)return null;const site=await query('select 1 from customer_sites where id=$1 and customer_id=$2 and company_id=$3',[data.siteId,job.rows[0].customer_id,user.companyId]);if(!site.rowCount)return null;}let name='Unassigned',uid=data.engineerUid||null,profileId=data.engineerId||null;if(profileId){const engineer=await query(`select full_name,user_uid from engineer_profiles where id=$1 and company_id=$2 and status<>'Inactive'`,[profileId,user.companyId]);if(!engineer.rowCount)return null;name=engineer.rows[0].full_name;uid=engineer.rows[0].user_uid}else if(uid){const engineer=await query(`select full_name from app_users where firebase_uid=$1 and company_id=$2 and role='engineer' and is_active=true`,[uid,user.companyId]);if(!engineer.rowCount)return null;name=engineer.rows[0].full_name;const profile=await query('select id from engineer_profiles where user_uid=$1 and company_id=$2',[uid,user.companyId]);profileId=profile.rows[0]?.id||null}const r=await query(`update jobs set site_id=coalesce($3,site_id),assigned_engineer_uid=$4,engineer_profile_id=$5,engineer_name=$6,scheduled_start=$7::timestamptz,scheduled_end=$8::timestamptz,status=case when status='Pending' and $7::timestamptz is not null then 'Scheduled' else status end,updated_at=now() where id=$1 and company_id=$2 returning *`,[id,user.companyId,data.siteId,uid,profileId,name,data.scheduledStart,data.scheduledEnd]);return r.rowCount?mapJob(r.rows[0]):null;},
  async addJobNote(id,data,user){if(!pool)return{id:randomUUID(),body:data.body,author:user.fullName};const job=await query(`select 1 from jobs j where id=$1 and company_id=$2 and ($3<>'engineer' or assigned_engineer_uid=$4 or exists(select 1 from engineer_profiles ep where ep.id=j.engineer_profile_id and ep.user_uid=$4))`,[id,user.companyId,user.role,user.uid]);if(!job.rowCount)return null;const r=await query(`insert into job_notes(company_id,job_id,author_uid,body) values($1,$2,$3,$4) returning id,body,created_at "createdAt"`,[user.companyId,id,user.uid,data.body]);return{...r.rows[0],author:user.fullName};},
  async getJobCompletion(id,user){if(!pool)return{checklist:[],equipment:[],photos:[]};const owner=await query(`select 1 from jobs j where j.id=$1 and j.company_id=$2 and ($3<>'engineer' or j.assigned_engineer_uid=$4 or exists(select 1 from engineer_profiles ep where ep.id=j.engineer_profile_id and ep.user_uid=$4))`,[id,user.companyId,user.role,user.uid]);if(!owner.rowCount)return null;const [record,photos]=await Promise.all([query(`select checklist,equipment,work_summary "workSummary",further_work_required "furtherWorkRequired",customer_name "customerName",customer_signature "customerSignature",signed_at "signedAt",completed_at "completedAt" from job_completion_records where job_id=$1 and company_id=$2`,[id,user.companyId]),query(`select id,caption,mime_type "mimeType",created_at "createdAt" from job_photos where job_id=$1 and company_id=$2 order by created_at`,[id,user.companyId])]);return{checklist:record.rows[0]?.checklist||[],equipment:record.rows[0]?.equipment||[],workSummary:record.rows[0]?.workSummary||'',furtherWorkRequired:record.rows[0]?.furtherWorkRequired||'',customerName:record.rows[0]?.customerName||'',customerSignature:record.rows[0]?.customerSignature||null,signedAt:record.rows[0]?.signedAt||null,completedAt:record.rows[0]?.completedAt||null,photos:photos.rows};},
  async saveJobCompletion(id,data,user){if(!pool)return data;const owner=await query(`select 1 from jobs j where j.id=$1 and j.company_id=$2 and ($3<>'engineer' or j.assigned_engineer_uid=$4 or exists(select 1 from engineer_profiles ep where ep.id=j.engineer_profile_id and ep.user_uid=$4))`,[id,user.companyId,user.role,user.uid]);if(!owner.rowCount)return null;const r=await query(`insert into job_completion_records(job_id,company_id,checklist,equipment,work_summary,further_work_required,customer_name,customer_signature,signed_at) values($1,$2,$3::jsonb,$4::jsonb,$5,$6,$7,$8::text,case when $8::text is null then null else now() end) on conflict(job_id) do update set checklist=excluded.checklist,equipment=excluded.equipment,work_summary=excluded.work_summary,further_work_required=excluded.further_work_required,customer_name=excluded.customer_name,customer_signature=excluded.customer_signature,signed_at=case when excluded.customer_signature is null then job_completion_records.signed_at else now() end,updated_at=now() returning completed_at "completedAt"`,[id,user.companyId,JSON.stringify(data.checklist),JSON.stringify(data.equipment),data.workSummary,data.furtherWorkRequired,data.customerName,data.customerSignature]);return{...data,completedAt:r.rows[0].completedAt};},
  async addJobPhoto(id,image,mime,caption,user){if(!pool)return{id:randomUUID(),caption,mimeType:mime};const owner=await query(`select 1 from jobs j where j.id=$1 and j.company_id=$2 and ($3<>'engineer' or j.assigned_engineer_uid=$4 or exists(select 1 from engineer_profiles ep where ep.id=j.engineer_profile_id and ep.user_uid=$4))`,[id,user.companyId,user.role,user.uid]);if(!owner.rowCount)return null;const r=await query(`insert into job_photos(company_id,job_id,caption,mime_type,image_data,uploaded_by) values($1,$2,$3,$4,$5,$6) returning id,caption,mime_type "mimeType",created_at "createdAt"`,[user.companyId,id,caption,mime,image,user.uid]);return r.rows[0];},
  async getJobPhoto(jobId,photoId,user){if(!pool)return null;const r=await query(`select p.mime_type mime,p.image_data data from job_photos p join jobs j on j.id=p.job_id where p.id=$1 and p.job_id=$2 and p.company_id=$3 and ($4<>'engineer' or j.assigned_engineer_uid=$5 or exists(select 1 from engineer_profiles ep where ep.id=j.engineer_profile_id and ep.user_uid=$5))`,[photoId,jobId,user.companyId,user.role,user.uid]);return r.rows[0]||null;},
  async completeJob(id,user){if(!pool)return null;const client=await pool.connect();try{await client.query('begin');const owner=await client.query(`select j.status from jobs j where j.id=$1 and j.company_id=$2 and ($3<>'engineer' or j.assigned_engineer_uid=$4 or exists(select 1 from engineer_profiles ep where ep.id=j.engineer_profile_id and ep.user_uid=$4)) for update`,[id,user.companyId,user.role,user.uid]);if(!owner.rowCount){await client.query('rollback');return null}const record=await client.query(`select * from job_completion_records where job_id=$1 and company_id=$2 for update`,[id,user.companyId]);if(!record.rowCount)throw Object.assign(new Error('Save the completion form before completing this job.'),{status:400});const form=record.rows[0],checklist=Array.isArray(form.checklist)?form.checklist:JSON.parse(form.checklist||'[]');if(!form.work_summary||!form.customer_name||!form.customer_signature||!checklist.length||checklist.some(x=>!x.checked))throw Object.assign(new Error('Complete every checklist item, work summary and customer sign-off first.'),{status:400});await client.query(`update job_completion_records set completed_by=$3,completed_at=coalesce(completed_at,now()),updated_at=now() where job_id=$1 and company_id=$2`,[id,user.companyId,user.uid]);await client.query(`update jobs set status='Completed',completed_at=coalesce(completed_at,now()),updated_at=now() where id=$1 and company_id=$2`,[id,user.companyId]);if(owner.rows[0].status!=='Completed')await client.query(`insert into job_status_history(company_id,job_id,from_status,to_status,changed_by,note) values($1,$2,$3,'Completed',$4,'Engineer completion form and customer sign-off recorded')`,[user.companyId,id,owner.rows[0].status,user.uid]);await client.query('commit');return{status:'Completed'};}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async getServiceReport(id,user){if(!pool)return null;const r=await query(`select j.*,c.company_name customer_company,c.contact_name,c.email customer_email,c.address customer_address,s.name site_name,s.address site_address,s.postcode site_postcode,co.name company_name,co.email company_email,co.phone company_phone,co.address company_address,co.logo_data company_logo_data,u.full_name completed_by_name,cr.checklist,cr.equipment,cr.work_summary,cr.further_work_required,cr.customer_name signatory_name,cr.customer_signature,cr.signed_at,cr.completed_at report_completed_at from jobs j join customers c on c.id=j.customer_id left join customer_sites s on s.id=j.site_id join companies co on co.id=j.company_id join job_completion_records cr on cr.job_id=j.id left join app_users u on u.firebase_uid=cr.completed_by where j.id=$1 and j.company_id=$2 and ($3<>'engineer' or j.assigned_engineer_uid=$4 or exists(select 1 from engineer_profiles ep where ep.id=j.engineer_profile_id and ep.user_uid=$4))`,[id,user.companyId,user.role,user.uid]);if(!r.rowCount)return null;const x=r.rows[0],photos=await query(`select caption,mime_type,image_data from job_photos where job_id=$1 and company_id=$2 order by created_at`,[id,user.companyId]);return{type:'service-report',reference:x.reference,title:x.title,status:x.status,jobType:x.job_type,priority:x.priority,description:x.description,scheduledStart:x.scheduled_start,completedAt:x.report_completed_at,engineerName:x.completed_by_name||x.engineer_name,workSummary:x.work_summary,furtherWorkRequired:x.further_work_required,checklist:x.checklist,equipment:x.equipment,customerName:x.signatory_name,signatureBase64:x.customer_signature?.split(',')[1]||null,signedAt:x.signed_at,logoBase64:x.company_logo_data?.toString('base64'),company:{name:x.company_name,email:x.company_email,phone:x.company_phone,address:x.company_address},customer:{name:x.contact_name,company:x.customer_company,email:x.customer_email,address:x.customer_address},site:{name:x.site_name,address:x.site_address,postcode:x.site_postcode},photos:photos.rows.map(p=>({caption:p.caption,mime:p.mime_type,dataBase64:p.image_data.toString('base64')}))};},
  async listQuotes(user){if(!pool)return[];const r=await query(`select q.id,q.reference,q.title,q.status,q.subtotal,q.discount,q.vat_amount "vatAmount",q.total,q.valid_until "validUntil",q.created_at "createdAt",c.company_name "customerName",(select d.status from document_deliveries d where d.document_type='quote' and d.document_id=q.id order by d.created_at desc limit 1) "deliveryStatus",(select j.id from jobs j where j.quote_id=q.id limit 1) "jobId" from quotes q join customers c on c.id=q.customer_id where q.company_id=$1 order by q.created_at desc`,[user.companyId]);return r.rows.map(x=>({...x,subtotal:Number(x.subtotal),discount:Number(x.discount),vatAmount:Number(x.vatAmount),total:Number(x.total)}));},
  async getQuote(id,user){if(!pool)return null;const r=await query(`select q.id,q.reference,q.customer_id "customerId",q.site_id "siteId",q.title,q.status,q.discount,q.vat_rate "vatRate",q.valid_until "validUntil",q.notes,exists(select 1 from jobs j where j.quote_id=q.id) or exists(select 1 from invoices i where i.quote_id=q.id) "converted" from quotes q where q.id=$1 and q.company_id=$2`,[id,user.companyId]);if(!r.rowCount)return null;const items=await query(`select description,quantity,unit_price "unitPrice" from quote_items where quote_id=$1 order by sort_order`,[id]);return{...r.rows[0],discount:Number(r.rows[0].discount),vatRate:Number(r.rows[0].vatRate),items:items.rows.map(x=>({...x,quantity:Number(x.quantity),unitPrice:Number(x.unitPrice) }))};},
  async createQuote(data,user){if(!pool)return{id:randomUUID(),...data};const client=await pool.connect();try{await client.query('begin');const customer=await client.query('select company_name from customers where id=$1 and company_id=$2',[data.customerId,user.companyId]);if(!customer.rowCount){await client.query('rollback');return null}if(data.siteId){const site=await client.query('select 1 from customer_sites where id=$1 and customer_id=$2 and company_id=$3',[data.siteId,data.customerId,user.companyId]);if(!site.rowCount){await client.query('rollback');return null}}const subtotal=money(data.items.reduce((sum,item)=>sum+item.quantity*item.unitPrice,0)),discount=money(Math.min(data.discount,subtotal)),taxable=money(subtotal-discount),vatAmount=money(taxable*data.vatRate/100),total=money(taxable+vatAmount);const q=await client.query(`insert into quotes(company_id,customer_id,site_id,reference,title,subtotal,discount,vat_rate,vat_amount,total,valid_until,notes,created_by) values($1,$2,$3,'QT-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('quote_reference_seq')::text,4,'0'),$4,$5,$6,$7,$8,$9,$10,$11,$12) returning *`,[user.companyId,data.customerId,data.siteId,data.title,subtotal,discount,data.vatRate,vatAmount,total,data.validUntil,data.notes,user.uid]);for(let i=0;i<data.items.length;i++){const item=data.items[i];await client.query('insert into quote_items(quote_id,description,quantity,unit_price,sort_order) values($1,$2,$3,$4,$5)',[q.rows[0].id,item.description,item.quantity,item.unitPrice,i])}await client.query('commit');return{id:q.rows[0].id,reference:q.rows[0].reference,customerName:customer.rows[0].company_name,title:data.title,status:'Draft',subtotal,discount,vatAmount,total,validUntil:data.validUntil};}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async updateQuote(id,data,user){if(!pool)return{id,...data,status:'Draft'};const client=await pool.connect();try{await client.query('begin');const existing=await client.query(`select q.id from quotes q where q.id=$1 and q.company_id=$2 for update`,[id,user.companyId]);if(!existing.rowCount){await client.query('rollback');return null}const converted=await client.query(`select exists(select 1 from jobs where quote_id=$1) or exists(select 1 from invoices where quote_id=$1) converted`,[id]);if(converted.rows[0].converted)throw Object.assign(new Error('This quotation has already been converted into a job or invoice and can no longer be edited.'),{status:409});const customer=await client.query('select company_name from customers where id=$1 and company_id=$2',[data.customerId,user.companyId]);if(!customer.rowCount)throw Object.assign(new Error('The selected customer is invalid.'),{status:400});if(data.siteId){const site=await client.query('select 1 from customer_sites where id=$1 and customer_id=$2 and company_id=$3',[data.siteId,data.customerId,user.companyId]);if(!site.rowCount)throw Object.assign(new Error('The selected site is invalid for this customer.'),{status:400})}const subtotal=money(data.items.reduce((sum,item)=>sum+item.quantity*item.unitPrice,0)),discount=money(Math.min(data.discount,subtotal)),taxable=money(subtotal-discount),vatAmount=money(taxable*data.vatRate/100),total=money(taxable+vatAmount);const q=await client.query(`update quotes set customer_id=$3,site_id=$4,title=$5,subtotal=$6,discount=$7,vat_rate=$8,vat_amount=$9,total=$10,valid_until=$11,notes=$12,status='Draft',updated_at=now() where id=$1 and company_id=$2 returning id,reference,status`,[id,user.companyId,data.customerId,data.siteId,data.title,subtotal,discount,data.vatRate,vatAmount,total,data.validUntil,data.notes]);await client.query('delete from quote_items where quote_id=$1',[id]);for(let i=0;i<data.items.length;i++){const item=data.items[i];await client.query('insert into quote_items(quote_id,description,quantity,unit_price,sort_order) values($1,$2,$3,$4,$5)',[id,item.description,item.quantity,item.unitPrice,i])}await client.query('commit');return{...q.rows[0],customerName:customer.rows[0].company_name,title:data.title,subtotal,discount,vatAmount,total,validUntil:data.validUntil};}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async setQuoteStatus(id,status,user){if(!pool)return null;const r=await query('update quotes set status=$3,updated_at=now() where id=$1 and company_id=$2 returning id,reference,status',[id,user.companyId,status]);return r.rows[0]||null;},
  async quoteToInvoice(id,user){if(!pool)return null;const client=await pool.connect();try{await client.query('begin');const q=await client.query(`select * from quotes where id=$1 and company_id=$2 and status='Accepted' for update`,[id,user.companyId]);if(!q.rowCount){await client.query('rollback');return null}const row=q.rows[0];const existing=await client.query('select * from invoices where quote_id=$1 and company_id=$2',[id,user.companyId]);if(existing.rowCount){await client.query('rollback');return existing.rows[0]}const invoice=await client.query(`insert into invoices(company_id,customer_id,quote_id,reference,status,subtotal,discount,vat_rate,vat_amount,total,balance,issued_at,due_at,notes) values($1,$2,$3,'INV-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('invoice_reference_seq')::text,4,'0'),'Draft',$4,$5,$6,$7,$8,$8,current_date,current_date+interval '14 days',$9) returning *`,[user.companyId,row.customer_id,id,row.subtotal,row.discount,row.vat_rate,row.vat_amount,row.total,row.notes]);await client.query(`insert into invoice_items(invoice_id,description,quantity,unit_price,sort_order) select $1,description,quantity,unit_price,sort_order from quote_items where quote_id=$2`,[invoice.rows[0].id,id]);await client.query('commit');return invoice.rows[0];}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async quoteToJob(id,data,user){if(!pool)return null;const client=await pool.connect();try{await client.query('begin');const q=await client.query(`select q.*,c.company_name customer_name,co.name company_name from quotes q join customers c on c.id=q.customer_id join companies co on co.id=q.company_id where q.id=$1 and q.company_id=$2 and q.status='Accepted' for update of q`,[id,user.companyId]);if(!q.rowCount){await client.query('rollback');return null}const quote=q.rows[0],existing=await client.query('select * from jobs where quote_id=$1 and company_id=$2',[id,user.companyId]);let engineer=null;if(data.engineerId){const e=await client.query(`select id,user_uid uid,full_name,email from engineer_profiles where id=$1 and company_id=$2 and status<>'Inactive'`,[data.engineerId,user.companyId]);if(!e.rowCount)throw Object.assign(new Error('The selected engineer is unavailable.'),{status:400});engineer=e.rows[0]}if(existing.rowCount){await client.query('commit');return{job:mapJob({...existing.rows[0],customer_name:quote.customer_name}),engineerEmail:null}}const lines=await client.query('select description,quantity from quote_items where quote_id=$1 order by sort_order',[id]);const description=[`Created from accepted quotation ${quote.reference}.`,...lines.rows.map(x=>`${Number(x.quantity)} x ${x.description}`),quote.notes].filter(Boolean).join('\n');const status=data.scheduledStart?'Scheduled':'Pending';const result=await client.query(`insert into jobs(reference,company_id,customer_id,site_id,quote_id,title,description,engineer_name,assigned_engineer_uid,engineer_profile_id,job_type,due_date,scheduled_start,scheduled_end,status,priority,created_by) values('JOB-'||lpad(nextval('job_reference_seq')::text,4,'0'),$1,$2,$3,$4,$5,$6,$7,$8,$9,'Installation',$10,$11,$12,$13,$14,$15) returning *`,[user.companyId,quote.customer_id,quote.site_id,id,quote.title,description,engineer?.full_name||'Unassigned',engineer?.uid||null,engineer?.id||null,data.dueDate,data.scheduledStart,data.scheduledEnd,status,data.priority,user.uid]);await client.query('insert into job_status_history(company_id,job_id,to_status,changed_by,note) values($1,$2,$3,$4,$5)',[user.companyId,result.rows[0].id,status,user.uid,`Created from quotation ${quote.reference}`]);await client.query('commit');return{job:mapJob({...result.rows[0],customer_name:quote.customer_name}),engineerEmail:engineer?.email||null,engineerName:engineer?.full_name||null,companyName:quote.company_name,customerName:quote.customer_name,quoteReference:quote.reference};}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async listInvoices(user){if(!pool)return[];const r=await query(`select i.id,i.reference,i.status,i.total,i.balance,i.issued_at "issuedAt",i.due_at "dueAt",c.company_name "customerName",(select d.status from document_deliveries d where d.document_type='invoice' and d.document_id=i.id order by d.created_at desc limit 1) "deliveryStatus" from invoices i join customers c on c.id=i.customer_id where i.company_id=$1 order by i.created_at desc`,[user.companyId]);return r.rows.map(x=>({...x,total:Number(x.total),balance:Number(x.balance)}));},
  async addPayment(id,data,user){if(!pool)return null;const client=await pool.connect();try{await client.query('begin');const invoice=await client.query('select total,balance from invoices where id=$1 and company_id=$2 for update',[id,user.companyId]);if(!invoice.rowCount||data.amount>Number(invoice.rows[0].balance)){await client.query('rollback');return null}await client.query('insert into invoice_payments(company_id,invoice_id,amount,method,reference,paid_at,recorded_by) values($1,$2,$3,$4,$5,coalesce($6,current_date),$7)',[user.companyId,id,data.amount,data.method,data.reference,data.paidAt||null,user.uid]);const balance=money(Number(invoice.rows[0].balance)-data.amount),status=balance===0?'Paid':'Part-paid';const r=await client.query('update invoices set balance=$3,status=$4 where id=$1 and company_id=$2 returning id,reference,status,total,balance',[id,user.companyId,balance,status]);await client.query('commit');return{...r.rows[0],total:Number(r.rows[0].total),balance:Number(r.rows[0].balance)};}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async getCommercialDocument(type,id,user){if(!pool)return null;const isQuote=type==='quote',table=isQuote?'quotes':'invoices',itemsTable=isQuote?'quote_items':'invoice_items';const r=await query(`select d.*,c.company_name customer_name,c.contact_name,c.email customer_email,c.address customer_address,co.name company_name,co.email company_email,co.phone company_phone,co.address company_address,co.logo_data company_logo_data from ${table} d join customers c on c.id=d.customer_id join companies co on co.id=d.company_id where d.id=$1 and d.company_id=$2`,[id,user.companyId]);if(!r.rowCount)return null;const items=await query(`select description,quantity,unit_price from ${itemsTable} where ${isQuote?'quote_id':'invoice_id'}=$1 order by sort_order`,[id]);const d=r.rows[0];return{type,reference:d.reference,status:d.status,title:d.title||`${type==='quote'?'Quotation':'Invoice'} ${d.reference}`,issued:new Date(d.created_at||d.issued_at||Date.now()).toLocaleDateString('en-GB'),dateLabel:isQuote?'Valid until':'Payment due',dateValue:d.valid_until||d.due_at||'-',logoBase64:d.company_logo_data?.toString('base64'),company:{name:d.company_name,email:d.company_email,phone:d.company_phone,address:d.company_address},customer:{name:d.customer_name,contact:d.contact_name,email:d.customer_email,address:d.customer_address},items:items.rows.map(x=>({description:x.description,quantity:Number(x.quantity),unitPrice:Number(x.unit_price)})),subtotal:Number(d.subtotal),discount:Number(d.discount),vatRate:Number(d.vat_rate),vatAmount:Number(d.vat_amount),total:Number(d.total),balance:isQuote?0:Number(d.balance),notes:d.notes||''};},
  async prepareDelivery(type,id,user){const document=await this.getCommercialDocument(type,id,user);if(!document)return null;if(!document.customer.email)throw Object.assign(new Error('This customer does not have an email address.'),{status:400});const r=await query(`insert into document_deliveries(company_id,document_type,document_id,recipient_email,sent_by) values($1,$2,$3,$4,$5) returning id,access_token "accessToken"`,[user.companyId,type,id,document.customer.email,user.uid]);return{document,delivery:r.rows[0]};},
  async finishDelivery(id,result,error=''){const status=error?'Failed':'Sent';const r=await query(`update document_deliveries set status=$2::varchar,provider_message_id=$3,error_message=$4,sent_at=case when $2::varchar='Sent' then now() else sent_at end where id=$1 returning *`,[id,status,result?.id||null,error||null]);return r.rows[0]||null;},
  async getPublicQuote(token){if(!pool)return null;const r=await query(`select q.id,q.reference,q.title,q.status,q.subtotal,q.discount,q.vat_rate,q.vat_amount,q.total,q.valid_until,q.notes,c.company_name customer_name,c.contact_name,co.name company_name,co.email company_email,d.status delivery_status,d.decided_at from document_deliveries d join quotes q on q.id=d.document_id and d.document_type='quote' join customers c on c.id=q.customer_id join companies co on co.id=q.company_id where d.access_token=$1`,[token]);if(!r.rowCount)return null;const x=r.rows[0],items=await query('select description,quantity,unit_price from quote_items where quote_id=$1 order by sort_order',[x.id]);return{reference:x.reference,title:x.title,status:x.status,deliveryStatus:x.delivery_status,companyName:x.company_name,companyEmail:x.company_email,customerName:x.customer_name,contactName:x.contact_name,subtotal:Number(x.subtotal),discount:Number(x.discount),vatRate:Number(x.vat_rate),vatAmount:Number(x.vat_amount),total:Number(x.total),validUntil:x.valid_until,notes:x.notes,decidedAt:x.decided_at,items:items.rows.map(i=>({description:i.description,quantity:Number(i.quantity),unitPrice:Number(i.unit_price)}))};},
  async decidePublicQuote(token,decision,name,ip){if(!pool)return null;const client=await pool.connect();try{await client.query('begin');const d=await client.query(`select id,document_id,status from document_deliveries where access_token=$1 and document_type='quote' for update`,[token]);if(!d.rowCount){await client.query('rollback');return null}if(['Accepted','Rejected'].includes(d.rows[0].status)){await client.query('rollback');return{alreadyDecided:true}}const status=decision==='accept'?'Accepted':'Rejected';await client.query('update quotes set status=$2,updated_at=now() where id=$1',[d.rows[0].document_id,status]);await client.query('update document_deliveries set status=$2,decided_at=now(),decision_name=$3,decision_ip=$4 where id=$1',[d.rows[0].id,status,name,ip||null]);await client.query('commit');return{status};}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async listEngineers(user){if(!pool)return[];const r=await query(`select e.id,e.user_uid "userUid",e.email,e.full_name "fullName",e.job_title "jobTitle",e.phone,e.skills,e.status,count(j.id)::int "jobCount" from engineer_profiles e left join jobs j on j.engineer_profile_id=e.id and j.status not in ('Completed','Cancelled') where e.company_id=$1 and e.status<>'Inactive' group by e.id order by e.full_name`,[user.companyId]);return r.rows;},
  async createEngineer(data,user){if(!pool)return{id:randomUUID(),...data,status:'Invited',jobCount:0};const client=await pool.connect();try{await client.query('begin');const existing=await client.query('select id from engineer_profiles where company_id=$1 and lower(email)=lower($2)',[user.companyId,data.email]);if(existing.rowCount)throw Object.assign(new Error('An engineer with this email already exists.'),{status:409});const profile=await client.query(`insert into engineer_profiles(company_id,email,full_name,job_title,phone,skills,created_by) values($1,lower($2),$3,$4,$5,$6,$7) returning id,email,full_name "fullName",job_title "jobTitle",phone,skills,status`,[user.companyId,data.email,data.fullName,data.jobTitle,data.phone,data.skills,user.uid]);await client.query(`update team_invitations set status='Cancelled' where company_id=$1 and lower(email)=lower($2) and status='Pending'`,[user.companyId,data.email]);await client.query(`insert into team_invitations(company_id,email,full_name,role,invited_by) values($1,lower($2),$3,'engineer',$4)`,[user.companyId,data.email,data.fullName,user.uid]);await client.query('commit');return{...profile.rows[0],jobCount:0,signupUrl:'http://localhost:5173/join'};}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async inviteCustomerPortal(customerId,data,user){if(!pool)return{...data,signupUrl:'http://localhost:5173/customer-join'};const customer=await query('select id from customers where id=$1 and company_id=$2',[customerId,user.companyId]);if(!customer.rowCount)return null;const member=await query('select 1 from app_users where company_id=$1 and lower(email)=lower($2)',[user.companyId,data.email]);if(member.rowCount)throw Object.assign(new Error('That email already has access to this company.'),{status:409});await query(`update team_invitations set status='Cancelled' where company_id=$1 and lower(email)=lower($2) and status='Pending'`,[user.companyId,data.email]);await query(`insert into team_invitations(company_id,customer_id,email,full_name,role,invited_by) values($1,$2,lower($3),$4,'customer',$5)`,[user.companyId,customerId,data.email,data.fullName,user.uid]);return{email:data.email,fullName:data.fullName,status:'Pending',signupUrl:'http://localhost:5173/customer-join'};},
  async getCustomerPortal(user){if(!pool||!user.customerId)return null;const customer=await query(`select c.*,co.name provider_name,co.email provider_email,co.phone provider_phone from customers c join companies co on co.id=c.company_id where c.id=$1 and c.company_id=$2`,[user.customerId,user.companyId]);if(!customer.rowCount)return null;const [quotes,invoices,jobsResult,sites,assets,requests]=await Promise.all([query(`select id,reference,title,status,total,valid_until "validUntil",created_at "createdAt" from quotes where customer_id=$1 and company_id=$2 order by created_at desc`,[user.customerId,user.companyId]),query(`select id,reference,status,total,balance,issued_at "issuedAt",due_at "dueAt" from invoices where customer_id=$1 and company_id=$2 order by created_at desc`,[user.customerId,user.companyId]),query(`select j.id,j.reference,j.title,j.status,j.priority,j.job_type "jobType",j.due_date "dueDate",j.scheduled_start "scheduledStart",j.completed_at "completedAt",s.name "siteName",exists(select 1 from job_completion_records cr where cr.job_id=j.id and cr.completed_at is not null) "reportReady" from jobs j left join customer_sites s on s.id=j.site_id where j.customer_id=$1 and j.company_id=$2 order by j.created_at desc`,[user.customerId,user.companyId]),query(`select id,name,address,postcode from customer_sites where customer_id=$1 and company_id=$2 order by name`,[user.customerId,user.companyId]),query(`select a.id,a.system_type "systemType",a.manufacturer,a.model,a.serial_number "serialNumber",a.installed_at "installedAt",a.warranty_expires_at "warrantyExpiresAt",a.maintenance_due_at "maintenanceDueAt",s.name "siteName" from customer_assets a left join customer_sites s on s.id=a.site_id where a.customer_id=$1 and a.company_id=$2 order by a.created_at desc`,[user.customerId,user.companyId]),query(`select r.id,r.subject,r.description,r.priority,r.status,r.created_at "createdAt",s.name "siteName" from service_requests r left join customer_sites s on s.id=r.site_id where r.customer_id=$1 and r.company_id=$2 order by r.created_at desc`,[user.customerId,user.companyId])]);const c=customer.rows[0];return{customer:{id:c.id,companyName:c.company_name,contactName:c.contact_name,email:c.email,phone:c.phone,address:c.address},provider:{name:c.provider_name,email:c.provider_email,phone:c.provider_phone},quotes:quotes.rows.map(x=>({...x,total:Number(x.total)})),invoices:invoices.rows.map(x=>({...x,total:Number(x.total),balance:Number(x.balance)})),jobs:jobsResult.rows,sites:sites.rows,assets:assets.rows,requests:requests.rows};},
  async createServiceRequest(data,user){if(!pool||!user.customerId)return null;if(data.siteId){const site=await query('select 1 from customer_sites where id=$1 and customer_id=$2 and company_id=$3',[data.siteId,user.customerId,user.companyId]);if(!site.rowCount)return null}const r=await query(`insert into service_requests(company_id,customer_id,site_id,subject,description,priority,submitted_by) values($1,$2,$3,$4,$5,$6,$7) returning id,subject,description,priority,status,created_at "createdAt"`,[user.companyId,user.customerId,data.siteId,data.subject,data.description,data.priority,user.uid]);return r.rows[0];},
  async listServiceRequests(user){if(!pool)return[];const r=await query(`select r.id,r.subject,r.description,r.priority,r.status,r.created_at "createdAt",r.updated_at "updatedAt",c.company_name "customerName",c.id "customerId",s.name "siteName",s.id "siteId",j.id "jobId",j.reference "jobReference" from service_requests r join customers c on c.id=r.customer_id left join customer_sites s on s.id=r.site_id left join jobs j on j.company_id=r.company_id and j.description like '%Service request: '||r.id::text||'%' where r.company_id=$1 order by case r.priority when 'Urgent' then 1 when 'High' then 2 when 'Normal' then 3 else 4 end,r.created_at desc`,[user.companyId]);return r.rows;},
  async updateServiceRequest(id,data,user){if(!pool)return null;const r=await query(`update service_requests set status=$3,priority=$4,updated_at=now() where id=$1 and company_id=$2 returning id,subject,status,priority,updated_at "updatedAt"`,[id,user.companyId,data.status,data.priority]);return r.rows[0]||null;},
  async serviceRequestToJob(id,data,user){if(!pool)return null;const client=await pool.connect();try{await client.query('begin');const request=await client.query(`select r.*,c.company_name customer_name from service_requests r join customers c on c.id=r.customer_id where r.id=$1 and r.company_id=$2 for update of r`,[id,user.companyId]);if(!request.rowCount){await client.query('rollback');return null}const item=request.rows[0],existing=await client.query(`select * from jobs where company_id=$1 and description like $2 limit 1`,[user.companyId,`%Service request: ${id}%`]);if(existing.rowCount){await client.query('commit');return mapJob({...existing.rows[0],customer_name:item.customer_name})}let engineer=null;if(data.engineerId){const e=await client.query(`select id,user_uid,full_name from engineer_profiles where id=$1 and company_id=$2 and status<>'Inactive'`,[data.engineerId,user.companyId]);if(!e.rowCount)throw Object.assign(new Error('The selected engineer is unavailable.'),{status:400});engineer=e.rows[0]}const status=data.scheduledStart?'Scheduled':'Pending',priority=item.priority==='Normal'?'Medium':item.priority;const result=await client.query(`insert into jobs(reference,company_id,customer_id,site_id,title,description,engineer_name,assigned_engineer_uid,engineer_profile_id,job_type,due_date,scheduled_start,scheduled_end,status,priority,created_by) values('JOB-'||lpad(nextval('job_reference_seq')::text,4,'0'),$1,$2,$3,$4,$5,$6,$7,$8,'Repair',$9,$10,$11,$12,$13,$14) returning *`,[user.companyId,item.customer_id,item.site_id,item.subject,`${item.description}\n\nService request: ${id}`,engineer?.full_name||'Unassigned',engineer?.user_uid||null,engineer?.id||null,data.dueDate,data.scheduledStart,data.scheduledEnd,status,priority,user.uid]);await client.query(`update service_requests set status='Scheduled',updated_at=now() where id=$1`,[id]);await client.query(`insert into job_status_history(company_id,job_id,to_status,changed_by,note) values($1,$2,$3,$4,'Created from customer service request')`,[user.companyId,result.rows[0].id,status,user.uid]);await client.query('commit');return mapJob({...result.rows[0],customer_name:item.customer_name});}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async customerOwnsJob(id,user){if(!pool||!user.customerId)return false;const r=await query('select 1 from jobs where id=$1 and customer_id=$2 and company_id=$3',[id,user.customerId,user.companyId]);return r.rowCount>0;},
  async customerOwnsDocument(type,id,user){if(!pool||!user.customerId)return false;const table=type==='quote'?'quotes':'invoices';const r=await query(`select 1 from ${table} where id=$1 and customer_id=$2 and company_id=$3`,[id,user.customerId,user.companyId]);return r.rowCount>0;},
  async listInventory(search,user){if(!pool)return[];const r=await query(`select i.id,i.sku,i.name,i.category,i.manufacturer,i.supplier,i.supplier_email "supplierEmail",i.unit_cost "unitCost",i.sale_price "salePrice",i.quantity,i.reorder_level "reorderLevel",i.location,i.created_at "createdAt",coalesce((select json_agg(m order by m."createdAt" desc) from (select id,movement_type "movementType",quantity_change "quantityChange",reference,notes,created_at "createdAt" from inventory_movements where item_id=i.id and company_id=i.company_id order by created_at desc limit 8)m),'[]'::json) movements from inventory_items i where i.company_id=$2 and i.is_active=true and ($1='' or i.name ilike '%'||$1||'%' or i.sku ilike '%'||$1||'%' or i.category ilike '%'||$1||'%' or i.supplier ilike '%'||$1||'%') order by case when i.quantity<=i.reorder_level then 0 else 1 end,i.name`,[search,user.companyId]);return r.rows.map(x=>({...x,unitCost:Number(x.unitCost),salePrice:Number(x.salePrice)}));},
  async createInventoryItem(data,user){if(!pool)return{id:randomUUID(),...data};const r=await query(`insert into inventory_items(company_id,sku,name,category,manufacturer,supplier,supplier_email,unit_cost,sale_price,quantity,reorder_level,location) values($1,upper($2),$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning id,sku,name,category,manufacturer,supplier,supplier_email "supplierEmail",unit_cost "unitCost",sale_price "salePrice",quantity,reorder_level "reorderLevel",location`,[user.companyId,data.sku,data.name,data.category,data.manufacturer,data.supplier,data.supplierEmail,data.unitCost,data.salePrice,data.quantity,data.reorderLevel,data.location]);return{...r.rows[0],unitCost:Number(r.rows[0].unitCost),salePrice:Number(r.rows[0].salePrice),movements:[]};},
  async addInventoryMovement(id,data,user){if(!pool)return null;const client=await pool.connect();try{await client.query('begin');const item=await client.query('select quantity from inventory_items where id=$1 and company_id=$2 and is_active=true for update',[id,user.companyId]);if(!item.rowCount){await client.query('rollback');return null}const next=item.rows[0].quantity+data.quantityChange;if(next<0)throw Object.assign(new Error('This adjustment would make the stock quantity negative.'),{status:400});await client.query(`insert into inventory_movements(company_id,item_id,movement_type,quantity_change,reference,notes,recorded_by) values($1,$2,$3,$4,$5,$6,$7)`,[user.companyId,id,data.movementType,data.quantityChange,data.reference,data.notes,user.uid]);const r=await client.query(`update inventory_items set quantity=$3,updated_at=now() where id=$1 and company_id=$2 returning id,quantity,reorder_level "reorderLevel"`,[id,user.companyId,next]);await client.query('commit');return r.rows[0];}catch(error){await client.query('rollback');throw error}finally{client.release()}},
  async archiveInventoryItem(id,user){if(!pool)return false;const r=await query('update inventory_items set is_active=false,updated_at=now() where id=$1 and company_id=$2',[id,user.companyId]);return r.rowCount>0;},
  async getAnalytics(months,user){if(!pool)return null;const [summary,monthly,types,statuses,engineers,customers]=await Promise.all([query(`select (select count(*)::int from jobs where company_id=$1 and status='Completed' and completed_at>=current_date-($2||' months')::interval) completed_jobs,(select count(*)::int from jobs where company_id=$1 and status not in ('Completed','Cancelled')) active_jobs,(select coalesce(sum(total-balance),0) from invoices where company_id=$1 and issued_at>=current_date-($2||' months')::interval) revenue,(select coalesce(sum(balance),0) from invoices where company_id=$1 and balance>0) outstanding,(select count(*)::int from customers where company_id=$1 and status='Active') active_customers,(select count(*)::int from service_requests where company_id=$1 and status in ('Submitted','Reviewing')) open_requests`,[user.companyId,months]),query(`with series as (select generate_series(date_trunc('month',current_date)-(($2-1)||' months')::interval,date_trunc('month',current_date),'1 month') as month_start) select to_char(s.month_start,'Mon YY') label,coalesce((select sum(i.total-i.balance) from invoices i where i.company_id=$1 and date_trunc('month',i.issued_at)=s.month_start),0) revenue,coalesce((select count(*) from jobs j where j.company_id=$1 and j.status='Completed' and date_trunc('month',j.completed_at)=s.month_start),0)::int completed from series s order by s.month_start`,[user.companyId,months]),query(`select job_type label,count(*)::int value from jobs where company_id=$1 and created_at>=current_date-($2||' months')::interval group by job_type order by value desc`,[user.companyId,months]),query(`select status label,count(*)::int value from jobs where company_id=$1 group by status order by value desc`,[user.companyId]),query(`select coalesce(e.full_name,j.engineer_name,'Unassigned') name,count(*)::int jobs,count(*) filter(where j.status='Completed')::int completed from jobs j left join engineer_profiles e on e.id=j.engineer_profile_id where j.company_id=$1 and j.created_at>=current_date-($2||' months')::interval group by coalesce(e.full_name,j.engineer_name,'Unassigned') order by completed desc,jobs desc limit 8`,[user.companyId,months]),query(`select c.company_name name,(select count(*)::int from jobs j where j.customer_id=c.id) jobs,(select coalesce(sum(i.total),0) from invoices i where i.customer_id=c.id) value from customers c where c.company_id=$1 order by value desc,jobs desc limit 8`,[user.companyId])]);const s=summary.rows[0];return{summary:{completedJobs:s.completed_jobs,activeJobs:s.active_jobs,revenue:Number(s.revenue),outstanding:Number(s.outstanding),activeCustomers:s.active_customers,openRequests:s.open_requests},monthly:monthly.rows.map(x=>({...x,revenue:Number(x.revenue)})),jobTypes:types.rows,jobStatuses:statuses.rows,engineers:engineers.rows,customers:customers.rows.map(x=>({...x,value:Number(x.value)}))};},
  async getAssistantContext(user){
    if(!pool||!user.companyId){
      return {company:{name:'SecureVision Demo',currency:'GBP'},summary:{completedJobs:0,activeJobs:jobs.length,revenue:0,outstanding:0,activeCustomers:customers.length,openRequests:0},upcoming:jobs,overdue:[],unassigned:jobs.filter(x=>!x.engineerName||x.engineerName==='Unassigned'),lowStock:[],urgentRequests:[],engineers:[],topCustomers:[]};
    }
    const [company,analytics,upcoming,overdue,unassigned,lowStock,urgentRequests]=await Promise.all([
      this.getCompany(user),
      this.getAnalytics(6,user),
      query(`select j.reference,j.title,j.status,j.priority,j.due_date "dueDate",j.scheduled_start "scheduledStart",coalesce(e.full_name,j.engineer_name,'Unassigned') "engineerName",c.company_name "customerName" from jobs j join customers c on c.id=j.customer_id left join engineer_profiles e on e.id=j.engineer_profile_id where j.company_id=$1 and j.status not in ('Completed','Cancelled') order by coalesce(j.scheduled_start,j.due_date::timestamp) asc limit 12`,[user.companyId]),
      query(`select j.reference,j.title,j.due_date "dueDate",c.company_name "customerName" from jobs j join customers c on c.id=j.customer_id where j.company_id=$1 and j.status not in ('Completed','Cancelled') and j.due_date<current_date order by j.due_date limit 12`,[user.companyId]),
      query(`select reference,title,due_date "dueDate" from jobs where company_id=$1 and status not in ('Completed','Cancelled') and assigned_engineer_uid is null and engineer_profile_id is null order by due_date limit 12`,[user.companyId]),
      query(`select sku,name,quantity,reorder_level "reorderLevel" from inventory_items where company_id=$1 and is_active=true and quantity<=reorder_level order by quantity-reorder_level limit 12`,[user.companyId]),
      query(`select r.subject,r.priority,r.status,c.company_name "customerName" from service_requests r join customers c on c.id=r.customer_id where r.company_id=$1 and r.status in ('Submitted','Reviewing') and r.priority in ('Urgent','High') order by case r.priority when 'Urgent' then 1 else 2 end,r.created_at limit 10`,[user.companyId]),
    ]);
    return {company:{name:company.name,currency:company.currency,services:company.services},summary:analytics.summary,upcoming:upcoming.rows,overdue:overdue.rows,unassigned:unassigned.rows,lowStock:lowStock.rows,urgentRequests:urgentRequests.rows,engineers:analytics.engineers.map(x=>({...x,jobs:Number(x.jobs),completed:Number(x.completed)})),topCustomers:analytics.customers};
  },
  async getQuoteDraftContext(data,user){
    const [company,customer,inventory]=await Promise.all([this.getCompany(user),this.getCustomer(data.customerId,user),this.listInventory('',user)]);
    if(!company||!customer)return null;
    const site=data.siteId?customer.sites.find(item=>item.id===data.siteId):null;
    if(data.siteId&&!site)return null;
    return {company:{name:company.name,currency:company.currency,services:company.services},customer:{id:customer.id,name:customer.companyName},site:site?{id:site.id,name:site.name,address:site.address,postcode:site.postcode}:null,inventory:inventory.filter(item=>item.quantity>0).map(item=>({id:item.id,sku:item.sku,name:item.name,category:item.category,manufacturer:item.manufacturer,salePrice:item.salePrice,available:item.quantity}))};
  },
  async listNotifications(user){
    if(!pool||!user.companyId)return[];
    const r=await query(`with events as (
      select 'request:'||r.id::text notification_key,'Service request' type,r.subject title,c.company_name||' submitted a '||lower(r.priority)||' priority request.' message,'/app/requests' link,r.created_at event_at
      from service_requests r join customers c on c.id=r.customer_id
      where r.company_id=$1 and r.status in ('Submitted','Reviewing')
      union all
      select 'quote:'||q.id::text||':'||q.status,'Quotation response',q.reference||' was '||lower(q.status),c.company_name||' responded to the quotation.','/app/quotes',coalesce(q.updated_at,q.created_at)
      from quotes q join customers c on c.id=q.customer_id
      where q.company_id=$1 and q.status in ('Accepted','Rejected')
      union all
      select 'job-complete:'||j.id::text,'Job completed',j.reference||' · '||j.title,c.company_name||' job has been completed and its service report is ready.','/app/jobs/'||j.id::text,coalesce(j.completed_at,j.updated_at)
      from jobs j join customers c on c.id=j.customer_id
      where j.company_id=$1 and j.status='Completed'
      union all
      select 'stock:'||i.id::text||':'||i.quantity::text,'Low stock',i.name||' · '||i.quantity::text||' remaining','Stock has reached or fallen below its reorder level of '||i.reorder_level::text||'.','/app/inventory',i.updated_at
      from inventory_items i where i.company_id=$1 and i.is_active=true and i.quantity<=i.reorder_level
    ) select e.notification_key "key",e.type,e.title,e.message,e.link,e.event_at "createdAt",(nr.notification_key is not null) "isRead"
      from events e left join notification_reads nr on nr.company_id=$1 and nr.user_uid=$2 and nr.notification_key=e.notification_key
      where e.event_at>=now()-interval '90 days' order by e.event_at desc limit 60`,[user.companyId,user.uid]);
    return r.rows;
  },
  async markNotificationRead(key,user){
    if(!pool||!user.companyId)return false;
    await query(`insert into notification_reads(company_id,user_uid,notification_key) values($1,$2,$3) on conflict(company_id,user_uid,notification_key) do update set read_at=now()`,[user.companyId,user.uid,key]);
    return true;
  },
  async markAllNotificationsRead(user){
    const items=await this.listNotifications(user);if(!pool||!items.length)return items.length;
    await query(`insert into notification_reads(company_id,user_uid,notification_key) select $1,$2,unnest($3::text[]) on conflict(company_id,user_uid,notification_key) do update set read_at=now()`,[user.companyId,user.uid,items.map(item=>item.key)]);
    return items.length;
  },
  async listDueReminders(user){
    if(!pool||!user.companyId)return[];
    const r=await query(`select j.id,j.reference,j.title,j.scheduled_start "scheduledStart",j.scheduled_end "scheduledEnd",coalesce(e.full_name,j.engineer_name,'To be confirmed') "engineerName",c.company_name "customerName",c.contact_name "contactName",c.email,s.name "siteName",s.address "siteAddress",s.postcode "sitePostcode",(ar.id is not null) "alreadySent",ar.sent_at "sentAt"
      from jobs j join customers c on c.id=j.customer_id left join customer_sites s on s.id=j.site_id left join engineer_profiles e on e.id=j.engineer_profile_id left join appointment_reminders ar on ar.job_id=j.id and ar.scheduled_start=j.scheduled_start and lower(ar.recipient)=lower(c.email)
      where j.company_id=$1 and j.status not in ('Completed','Cancelled') and j.scheduled_start between now() and now()+interval '72 hours' and c.email<>'' order by j.scheduled_start`,[user.companyId]);
    return r.rows;
  },
  async getReminderJob(id,user){
    if(!pool||!user.companyId)return null;
    const r=await query(`select j.id,j.reference,j.title,j.description,j.scheduled_start "scheduledStart",j.scheduled_end "scheduledEnd",coalesce(e.full_name,j.engineer_name,'To be confirmed') "engineerName",c.company_name "customerName",c.contact_name "contactName",c.email,s.name "siteName",s.address "siteAddress",s.postcode "sitePostcode",co.name "companyName",co.email "companyEmail"
      from jobs j join customers c on c.id=j.customer_id join companies co on co.id=j.company_id left join customer_sites s on s.id=j.site_id left join engineer_profiles e on e.id=j.engineer_profile_id
      where j.id=$1 and j.company_id=$2 and j.status not in ('Completed','Cancelled') and j.scheduled_start is not null and c.email<>''`,[id,user.companyId]);
    return r.rows[0]||null;
  },
  async recordReminder(job,messageId,user){
    if(!pool)return null;
    const r=await query(`insert into appointment_reminders(company_id,job_id,scheduled_start,recipient,message_id,sent_by) values($1,$2,$3,$4,$5,$6) on conflict(job_id,scheduled_start,recipient) do nothing returning id,sent_at "sentAt"`,[user.companyId,job.id,job.scheduledStart,job.email,messageId||'',user.uid]);
    return r.rows[0]||null;
  },
  async listAuditActivity(user){
    if(!pool||!user.companyId)return[];
    const r=await query(`with activity as (
      select h.id::text,'Job' category,'Status changed' action,j.reference||' · '||j.title subject,coalesce(h.from_status::text,'New')||' → '||h.to_status::text detail,h.created_at event_at,h.changed_by actor_uid,'/app/jobs/'||j.id::text link
      from job_status_history h join jobs j on j.id=h.job_id where h.company_id=$1
      union all
      select n.id::text,'Job','Note added',j.reference||' · '||j.title,left(n.body,300),n.created_at,n.author_uid,'/app/jobs/'||j.id::text
      from job_notes n join jobs j on j.id=n.job_id where n.company_id=$1
      union all
      select m.id::text,'Inventory',m.movement_type,i.sku||' · '||i.name,(case when m.quantity_change>0 then '+' else '' end)||m.quantity_change::text||' units'||case when m.reference<>'' then ' · '||m.reference else '' end,m.created_at,m.recorded_by,'/app/inventory'
      from inventory_movements m join inventory_items i on i.id=m.item_id where m.company_id=$1
      union all
      select d.id::text,'Document',case when d.decided_at is not null then d.status else 'Email '||d.status end,upper(d.document_type)||' sent to '||d.recipient_email,case when d.decision_name is not null then 'Customer response recorded for '||d.decision_name else coalesce(d.error_message,'Delivery activity') end,coalesce(d.decided_at,d.sent_at,d.created_at),d.sent_by,case when d.document_type='quote' then '/app/quotes' else '/app/invoices' end
      from document_deliveries d where d.company_id=$1
      union all
      select p.id::text,'Payment','Payment recorded',i.reference,'GBP '||to_char(p.amount,'FM999999990.00')||' · '||p.method||case when p.reference<>'' then ' · '||p.reference else '' end,p.created_at,p.recorded_by,'/app/invoices'
      from invoice_payments p join invoices i on i.id=p.invoice_id where p.company_id=$1
      union all
      select s.id::text,'Customer','Service request submitted',c.company_name||' · '||s.subject,s.priority||' priority · '||s.status,s.created_at,s.submitted_by,'/app/requests'
      from service_requests s join customers c on c.id=s.customer_id where s.company_id=$1
      union all
      select a.id::text,'Reminder','Appointment reminder sent',j.reference||' · '||j.title,'Sent to '||a.recipient,a.sent_at,a.sent_by,'/app/reminders'
      from appointment_reminders a join jobs j on j.id=a.job_id where a.company_id=$1
    ) select activity.id,activity.category,activity.action,activity.subject,activity.detail,activity.event_at "createdAt",activity.link,coalesce(u.full_name,u.email,case when activity.actor_uid is null then 'Customer / system' else 'Former team member' end) actor
      from activity left join app_users u on u.firebase_uid=activity.actor_uid order by activity.event_at desc limit 200`,[user.companyId]);
    return r.rows;
  },
  async listTeam(user){if(!pool)return{members:[],invitations:[]};const members=await query('select firebase_uid uid,email,full_name "fullName",role,is_active "isActive",created_at "createdAt" from app_users where company_id=$1 order by created_at',[user.companyId]);const invitations=await query(`select id,email,full_name "fullName",role,status,expires_at "expiresAt",created_at "createdAt" from team_invitations where company_id=$1 and status='Pending' order by created_at desc`,[user.companyId]);return{members:members.rows,invitations:invitations.rows};},
  async createInvitation(data,user){if(!pool)return{id:randomUUID(),...data,status:'Pending'};if(!user.companyId)throw Object.assign(new Error('Complete company onboarding first.'),{status:409});const existing=await query('select 1 from app_users where company_id=$1 and lower(email)=lower($2)',[user.companyId,data.email]);if(existing.rowCount)throw Object.assign(new Error('That person is already a company member.'),{status:409});await query(`update team_invitations set status='Cancelled' where company_id=$1 and lower(email)=lower($2) and status='Pending'`,[user.companyId,data.email]);const r=await query(`insert into team_invitations(company_id,email,full_name,role,invited_by) values($1,lower($2),$3,$4,$5) returning id,email,full_name "fullName",role,status,expires_at "expiresAt"`,[user.companyId,data.email,data.fullName,data.role,user.uid]);return{...r.rows[0],signupUrl:'http://127.0.0.1:5173/signup'};},
  async cancelInvitation(id,user){if(!pool)return true;const r=await query(`update team_invitations set status='Cancelled' where id=$1 and company_id=$2 and status='Pending'`,[id,user.companyId]);return r.rowCount>0;},
  async updateMember(uid,data,user){if(uid===user.uid&&(data.isActive===false||data.role&&data.role!=='admin'))throw Object.assign(new Error('You cannot remove your own administrator access.'),{status:400});if(!pool)return null;const fields=[],values=[uid,user.companyId];if(data.role!==undefined){values.push(data.role);fields.push(`role=$${values.length}`)}if(data.isActive!==undefined){values.push(data.isActive);fields.push(`is_active=$${values.length}`)}const r=await query(`update app_users set ${fields.join(',')},updated_at=now() where firebase_uid=$1 and company_id=$2 returning firebase_uid uid,email,full_name "fullName",role,is_active "isActive"`,values);return r.rows[0]||null;},
};

